#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BlockPlayerFlow

#include "Basic.hpp"

#include "BP_BlockPlayerFlow_classes.hpp"
#include "BP_BlockPlayerFlow_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_BlockPlayerFlow.BP_BlockPlayerFlow_C.ExecuteUbergraph_BP_BlockPlayerFlow
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_BlockPlayerFlow_C::ExecuteUbergraph_BP_BlockPlayerFlow(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BlockPlayerFlow_C", "ExecuteUbergraph_BP_BlockPlayerFlow");

	Params::BP_BlockPlayerFlow_C_ExecuteUbergraph_BP_BlockPlayerFlow Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BlockPlayerFlow.BP_BlockPlayerFlow_C.OnComplete
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUserWidget*                      Modal                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_BlockPlayerFlow_C::OnComplete(class UUserWidget* Modal)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BlockPlayerFlow_C", "OnComplete");

	Params::BP_BlockPlayerFlow_C_OnComplete Parms{};

	Parms.Modal = Modal;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BlockPlayerFlow.BP_BlockPlayerFlow_C.PrepareModal
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUserWidget*                      Modal                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_BlockPlayerFlow_C::PrepareModal(class UUserWidget* Modal)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BlockPlayerFlow_C", "PrepareModal");

	Params::BP_BlockPlayerFlow_C_PrepareModal Parms{};

	Parms.Modal = Modal;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BlockPlayerFlow.BP_BlockPlayerFlow_C.BlockPlayerComplete
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bSuccess                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// const struct FBPUniqueNetId&            NetId_0                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const class FString&                    Name_0                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UBP_BlockPlayerFlow_C::BlockPlayerComplete(bool bSuccess, const struct FBPUniqueNetId& NetId_0, const class FString& Name_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BlockPlayerFlow_C", "BlockPlayerComplete");

	Params::BP_BlockPlayerFlow_C_BlockPlayerComplete Parms{};

	Parms.bSuccess = bSuccess;
	Parms.NetId_0 = std::move(NetId_0);
	Parms.Name_0 = std::move(Name_0);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BlockPlayerFlow.BP_BlockPlayerFlow_C.Run
// (Event, Public, BlueprintEvent)

void UBP_BlockPlayerFlow_C::Run()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BlockPlayerFlow_C", "Run");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BlockPlayerFlow.BP_BlockPlayerFlow_C.ResetInputAndComplete
// (BlueprintCallable, BlueprintEvent)

void UBP_BlockPlayerFlow_C::ResetInputAndComplete()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BlockPlayerFlow_C", "ResetInputAndComplete");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BlockPlayerFlow.BP_BlockPlayerFlow_C.MakeExplanation
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class UW_ReportPlayer_ReasonButton_C*>&SelectedReasonButtons                                  (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
// class FString*                          Explanation                                            (Parm, OutParm, ZeroConstructor, HasGetValueTypeHash)

void UBP_BlockPlayerFlow_C::MakeExplanation(TArray<class UW_ReportPlayer_ReasonButton_C*>& SelectedReasonButtons, class FString* Explanation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BlockPlayerFlow_C", "MakeExplanation");

	Params::BP_BlockPlayerFlow_C_MakeExplanation Parms{};

	Parms.SelectedReasonButtons = std::move(SelectedReasonButtons);

	UObject::ProcessEvent(Func, &Parms);

	SelectedReasonButtons = std::move(Parms.SelectedReasonButtons);

	if (Explanation != nullptr)
		*Explanation = std::move(Parms.Explanation);
}


SDK_NAMESPACE_END
