#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ControllerDisconnectionFlow

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BP_ControllerDisconnectionFlow.BP_ControllerDisconnectionFlow_C.ExecuteUbergraph_BP_ControllerDisconnectionFlow
// 0x0048 (0x0048 - 0x0000)
struct BP_ControllerDisconnectionFlow_C_ExecuteUbergraph_BP_ControllerDisconnectionFlow final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUserWidget*                            K2Node_CustomEvent_Modal;                          // 0x0008(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class UUserWidget* Modal)>     K2Node_CreateDelegate_OutputDelegate;              // 0x0010(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void(class UUserWidget* Modal)>     K2Node_CreateDelegate_OutputDelegate_1;            // 0x0020(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          CallFunc_ShowCustomModalBP_ReturnValue;            // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_GetFocusedWidget_ReturnValue;             // 0x0038(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUserWidget*                            K2Node_CustomEvent_Modal_1;                        // 0x0040(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_ControllerDisconnectionFlow_C_ExecuteUbergraph_BP_ControllerDisconnectionFlow;

// Function BP_ControllerDisconnectionFlow.BP_ControllerDisconnectionFlow_C.HandleComplete
// 0x0008 (0x0008 - 0x0000)
struct BP_ControllerDisconnectionFlow_C_HandleComplete final
{
public:
	class UUserWidget*                            Modal;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_ControllerDisconnectionFlow_C_HandleComplete;

// Function BP_ControllerDisconnectionFlow.BP_ControllerDisconnectionFlow_C.Prepare
// 0x0008 (0x0008 - 0x0000)
struct BP_ControllerDisconnectionFlow_C_Prepare final
{
public:
	class UUserWidget*                            Modal;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_ControllerDisconnectionFlow_C_Prepare;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
