#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ControllerDisconnectionFlow

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Backrooms_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_ControllerDisconnectionFlow.BP_ControllerDisconnectionFlow_C
// 0x0018 (0x00C0 - 0x00A8)
class UBP_ControllerDisconnectionFlow_C final : public UFancyUserFlow
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00A8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidget*                                FocusedWidget;                                     // 0x00B0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UW_ControllerDisconnectNotification_C*  ControllerWidgetRef;                               // 0x00B8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_ControllerDisconnectionFlow(int32 EntryPoint);
	void HandleComplete(class UUserWidget* Modal);
	void Prepare(class UUserWidget* Modal);
	void Run();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ControllerDisconnectionFlow_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ControllerDisconnectionFlow_C")
	}
	static class UBP_ControllerDisconnectionFlow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ControllerDisconnectionFlow_C>();
	}
};
DUMPER7_ASSERTS_UBP_ControllerDisconnectionFlow_C;

SDK_NAMESPACE_END
