#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DroppedItem

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Backrooms_structs.hpp"
#include "Backrooms_classes.hpp"
#include "EN_ItemRarity_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_DroppedItem.BP_DroppedItem_C
// 0x0018 (0x0270 - 0x0258)
class ABP_DroppedItem_C : public ADroppedItem
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0258(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetComponent*                       Widget;                                            // 0x0260(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	bool                                          EnableForFocus;                                    // 0x0268(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_BP_DroppedItem(int32 EntryPoint);
	void ToggleEvent(bool Enable);
	void OnEventLoaded(EEventType EventType);
	void OnBeginFocus();
	void OnEndFocus();
	void ReceiveBeginPlay();
	void CollisionOff();
	void CollisionOn();
	void ExamineModeOff();
	void ExamineModeOn();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_DroppedItem_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_DroppedItem_C")
	}
	static class ABP_DroppedItem_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_DroppedItem_C>();
	}
};
DUMPER7_ASSERTS_ABP_DroppedItem_C;

SDK_NAMESPACE_END
