#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DroppedItem_Glowstick

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "BP_DroppedItem_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_DroppedItem_Glowstick.BP_DroppedItem_Glowstick_C
// 0x0048 (0x02B8 - 0x0270)
class ABP_DroppedItem_Glowstick_C : public ABP_DroppedItem_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_DroppedItem_Glowstick_C;         // 0x0270(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USpotLightComponent*                    SpotLight;                                         // 0x0278(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UPointLightComponent*                   PointLight;                                        // 0x0280(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	struct FGuid                                  GlowstickID;                                       // 0x0288(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          ShouldGlow;                                        // 0x0298(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)
	uint8                                         Pad_299[0x7];                                      // 0x0299(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_Glowstick_Component_C*              GlowstickComponent;                                // 0x02A0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               SpotlightRotation;                                 // 0x02A8(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)
	bool                                          IsSpawned;                                         // 0x02B4(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)

public:
	void ExecuteUbergraph_BP_DroppedItem_Glowstick(int32 EntryPoint);
	void ReceiveBeginPlay();
	void ReceiveDestroyed();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_DroppedItem_Glowstick_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_DroppedItem_Glowstick_C")
	}
	static class ABP_DroppedItem_Glowstick_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_DroppedItem_Glowstick_C>();
	}
};
DUMPER7_ASSERTS_ABP_DroppedItem_Glowstick_C;

SDK_NAMESPACE_END
