#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_EULA_Flow

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Backrooms_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_EULA_Flow.BP_EULA_Flow_C
// 0x0028 (0x00D0 - 0x00A8)
class UBP_EULA_Flow_C final : public UFancyUserFlow
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00A8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class FString                                 GameSettings_SlotName;                             // 0x00B0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	class UWidget*                                PrevFocusedWidget;                                 // 0x00C0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bDidAcceptEULA;                                    // 0x00C8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          bDebugEULA;                                        // 0x00C9(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_BP_EULA_Flow(int32 EntryPoint);
	void OnCompleteModal(class UUserWidget* Modal);
	void PrepareModal(class UUserWidget* Modal);
	void Run();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_EULA_Flow_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_EULA_Flow_C")
	}
	static class UBP_EULA_Flow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_EULA_Flow_C>();
	}
};
DUMPER7_ASSERTS_UBP_EULA_Flow_C;

SDK_NAMESPACE_END
