#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FindSessionFlow

#include "Basic.hpp"

#include "BP_FindSessionFlow_classes.hpp"
#include "BP_FindSessionFlow_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_FindSessionFlow.BP_FindSessionFlow_C.ExecuteUbergraph_BP_FindSessionFlow
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_FindSessionFlow_C::ExecuteUbergraph_BP_FindSessionFlow(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FindSessionFlow_C", "ExecuteUbergraph_BP_FindSessionFlow");

	Params::BP_FindSessionFlow_C_ExecuteUbergraph_BP_FindSessionFlow Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FindSessionFlow.BP_FindSessionFlow_C.Run
// (Event, Public, BlueprintEvent)

void UBP_FindSessionFlow_C::Run()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FindSessionFlow_C", "Run");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_FindSessionFlow.BP_FindSessionFlow_C.OnSuccess_C619554E4A736403075EDF9C053CCDC1
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const TArray<struct FBlueprintSessionResult>&Results_0                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UBP_FindSessionFlow_C::OnSuccess_C619554E4A736403075EDF9C053CCDC1(const TArray<struct FBlueprintSessionResult>& Results_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FindSessionFlow_C", "OnSuccess_C619554E4A736403075EDF9C053CCDC1");

	Params::BP_FindSessionFlow_C_OnSuccess_C619554E4A736403075EDF9C053CCDC1 Parms{};

	Parms.Results_0 = std::move(Results_0);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FindSessionFlow.BP_FindSessionFlow_C.OnFailure_C619554E4A736403075EDF9C053CCDC1
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const TArray<struct FBlueprintSessionResult>&Results_0                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UBP_FindSessionFlow_C::OnFailure_C619554E4A736403075EDF9C053CCDC1(const TArray<struct FBlueprintSessionResult>& Results_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FindSessionFlow_C", "OnFailure_C619554E4A736403075EDF9C053CCDC1");

	Params::BP_FindSessionFlow_C_OnFailure_C619554E4A736403075EDF9C053CCDC1 Parms{};

	Parms.Results_0 = std::move(Results_0);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FindSessionFlow.BP_FindSessionFlow_C.Cancel
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_FindSessionFlow_C::Cancel()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FindSessionFlow_C", "Cancel");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
