#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Glowstick_Component

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Glowstick_Component.BP_Glowstick_Component_C
// 0x0010 (0x00C0 - 0x00B0)
class UBP_Glowstick_Component_C final : public UActorComponent
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USpotLightComponent*                    SpotLight;                                         // 0x00B8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_Glowstick_Component(int32 EntryPoint);
	void TickPointlight(class UPointLightComponent* PointLight, const struct FVector& ForwardVector);
	void TickSpotlight(class USpotLightComponent* SpotLight_0);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Glowstick_Component_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Glowstick_Component_C")
	}
	static class UBP_Glowstick_Component_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Glowstick_Component_C>();
	}
};
DUMPER7_ASSERTS_UBP_Glowstick_Component_C;

SDK_NAMESPACE_END
