#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Juice

#include "Basic.hpp"

#include "BP_Item_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Juice.BP_Juice_C
// 0x0038 (0x0290 - 0x0258)
class ABP_Juice_C final : public ABP_Item_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_Juice_C;                         // 0x0258(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UStaticMeshComponent*                   StaticMesh1;                                       // 0x0260(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x0268(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         Timeline_0_Alpha_4F50821D455C8CB87F6269AF25F4310D; // 0x0270(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Timeline_0_Drink_4F50821D455C8CB87F6269AF25F4310D; // 0x0274(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            Timeline_0__Direction_4F50821D455C8CB87F6269AF25F4310D; // 0x0278(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_279[0x7];                                      // 0x0279(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     Timeline_0;                                        // 0x0280(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               DynamicMaterial;                                   // 0x0288(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_Juice(int32 EntryPoint);
	void SRV_FinishDrink();
	void PlayAnimation();
	void OnCompleted_8D6BB16145C244F54B6DA5B60D5650E0(class FName NotifyName);
	void OnBlendOut_8D6BB16145C244F54B6DA5B60D5650E0(class FName NotifyName);
	void OnInterrupted_8D6BB16145C244F54B6DA5B60D5650E0(class FName NotifyName);
	void OnNotifyBegin_8D6BB16145C244F54B6DA5B60D5650E0(class FName NotifyName);
	void OnNotifyEnd_8D6BB16145C244F54B6DA5B60D5650E0(class FName NotifyName);
	void Timeline_0__UpdateFunc();
	void Timeline_0__FinishedFunc();
	void ReceiveBeginPlay();
	void UseItem();
	void SetMaterial(bool EnabledFOV);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Juice_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Juice_C")
	}
	static class ABP_Juice_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Juice_C>();
	}
};
DUMPER7_ASSERTS_ABP_Juice_C;

SDK_NAMESPACE_END
