#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SimpleFancyError

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Backrooms_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_SimpleFancyError.BP_SimpleFancyError_C
// 0x0070 (0x0118 - 0x00A8)
class UBP_SimpleFancyError_C final : public UFancyUserFlow
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00A8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class FText                                   Title;                                             // 0x00B0(0x0018)(Edit, BlueprintVisible, ExposeOnSpawn)
	class FText                                   Message;                                           // 0x00C8(0x0018)(Edit, BlueprintVisible, ExposeOnSpawn)
	class FText                                   Header;                                            // 0x00E0(0x0018)(Edit, BlueprintVisible, ExposeOnSpawn)
	class FText                                   OkButton;                                          // 0x00F8(0x0018)(Edit, BlueprintVisible, ExposeOnSpawn)
	bool                                          bForceReturnToMenu;                                // 0x0110(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)

public:
	void ExecuteUbergraph_BP_SimpleFancyError(int32 EntryPoint);
	void Run();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SimpleFancyError_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SimpleFancyError_C")
	}
	static class UBP_SimpleFancyError_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_SimpleFancyError_C>();
	}
};
DUMPER7_ASSERTS_UBP_SimpleFancyError_C;

SDK_NAMESPACE_END
