#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPFL_EntitySighting

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BPFL_EntitySighting.BPFL_EntitySighting_C
// 0x0000 (0x0028 - 0x0028)
class UBPFL_EntitySighting_C final : public UBlueprintFunctionLibrary
{
public:
	static void CallOnEntitySighted_Controller(class AController* OwningController, class UObject* __WorldContext);
	static void CallOnEntitySighted_Actor(class AActor* OwningActor, class UObject* __WorldContext);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPFL_EntitySighting_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPFL_EntitySighting_C")
	}
	static class UBPFL_EntitySighting_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPFL_EntitySighting_C>();
	}
};
DUMPER7_ASSERTS_UBPFL_EntitySighting_C;

SDK_NAMESPACE_END
