#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPFL_ControllerSupport

#include "Basic.hpp"

#include "Engine_classes.hpp"
#include "SlateCore_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BPFL_ControllerSupport.BPFL_ControllerSupport_C
// 0x0000 (0x0028 - 0x0028)
class UBPFL_ControllerSupport_C final : public UBlueprintFunctionLibrary
{
public:
	static void GetGridNavigationNextIndex(int32 CurrentIndex, int32 ArrayLength, int32 Columns, EUINavigation Direction, class UObject* __WorldContext, int32* NewIndex);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPFL_ControllerSupport_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPFL_ControllerSupport_C")
	}
	static class UBPFL_ControllerSupport_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPFL_ControllerSupport_C>();
	}
};
DUMPER7_ASSERTS_UBPFL_ControllerSupport_C;

SDK_NAMESPACE_END
