#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_KeyboardInteraction

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BPI_KeyboardInteraction.BPI_KeyboardInteraction_C.SetComponentReference
// 0x0008 (0x0008 - 0x0000)
struct BPI_KeyboardInteraction_C_SetComponentReference final
{
public:
	class UWidgetInteractionComponent*            WidgetInteractionComponent;                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPI_KeyboardInteraction_C_SetComponentReference;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
