#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ClimbSequence

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "LevelSequence_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass ClimbSequence.SequenceDirector_C
// 0x0008 (0x0040 - 0x0038)
class ClimbSequence::USequenceDirector_C final : public ULevelSequenceDirector
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0038(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_SequenceDirector(int32 EntryPoint);
	void SequenceEvent_0();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass ClimbSequence.SequenceDirector_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SequenceDirector_C")
	}
	static class ClimbSequence::USequenceDirector_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ClimbSequence::USequenceDirector_C>();
	}
};
DUMPER7_ASSERTS_ClimbSequence__USequenceDirector_C;

SDK_NAMESPACE_END
