#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: E_Ceiling_3x3_broken

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedEnum E_Ceiling_3x3_broken.E_Ceiling_3x3_broken
// NumValues: 0x0004
enum class E_Ceiling_3x3_broken : uint8
{
	NewEnumerator19                          = 0,
	NewEnumerator25                          = 1,
	NewEnumerator54                          = 2,
	E_Ceiling_3x3_MAX                        = 3,
};

SDK_NAMESPACE_END
