#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Flaregun_BP

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Flaregun_BP.Flaregun_BP_C
// 0x0018 (0x0238 - 0x0220)
class AFlaregun_BP_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0220(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UStaticMeshComponent*                   Flaregun;                                          // 0x0228(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0230(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_Flaregun_BP(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Flaregun_BP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Flaregun_BP_C")
	}
	static class AFlaregun_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AFlaregun_BP_C>();
	}
};
DUMPER7_ASSERTS_AFlaregun_BP_C;

SDK_NAMESPACE_END
