#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FoliageToSpawnInArea

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START

// UserDefinedStruct FoliageToSpawnInArea.FoliageToSpawnInArea
// 0x0030 (0x0030 - 0x0000)
struct FFoliageToSpawnInArea final
{
public:
	class UStaticMesh*                            FoliageToSpawn_Mesh_17_3C8F886546FA9128E267F1AF8A2DD0EF; // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 FoliageToSpawn_Component_18_1AD846B341447BD3BAE13DA58707FE6E; // 0x0008(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Density_5_54B823914D1C9E42333A53A256B62F6D;        // 0x0010(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Irregularity_7_23B801EB40FD74953D64AAA7EE571B92;   // 0x0014(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                minScale_10_AA532E8B44CC1FE88FD4EB8A0421516E;      // 0x0018(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                maxScale_12_D9B9070A4F83AF086F1B1A9DD537D137;      // 0x0024(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_FFoliageToSpawnInArea;

SDK_NAMESPACE_END
