#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Lobby_PlayerList

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "S_ConnectedPlayer_structs.hpp"
#include "AdvancedSessions_structs.hpp"
#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass Lobby_PlayerList.Lobby_PlayerList_C
// 0x0028 (0x0298 - 0x0270)
class ULobby_PlayerList_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0270(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UTextBlock*                             PlayerCount_Text;                                  // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UScrollBox*                             PlayerList;                                        // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TArray<struct FS_ConnectedPlayer>             ConnectedPlayers;                                  // 0x0288(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)

public:
	void ExecuteUbergraph_Lobby_PlayerList(int32 EntryPoint);
	void Update_Widget(const TArray<struct FS_ConnectedPlayer>& ConnectedPlayers_0);
	void CanClose();
	void Update_PlayerList();
	void Update_PlayerCount();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Lobby_PlayerList_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Lobby_PlayerList_C")
	}
	static class ULobby_PlayerList_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULobby_PlayerList_C>();
	}
};
DUMPER7_ASSERTS_ULobby_PlayerList_C;

SDK_NAMESPACE_END
