#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Lobby_Menu

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "E_Difficulty_structs.hpp"
#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass Lobby_Menu.Lobby_Menu_C
// 0x0060 (0x02D0 - 0x0270)
class ULobby_Menu_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0270(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class ULobby_MapSelection_C*                  Lobby_MapSelection;                                // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class ULobby_PlayerList_C*                    Lobby_PlayerList;                                  // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ReadyUpBtn;                                        // 0x0288(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_60;                                      // 0x0290(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class ALobby_GS_C*                            LobbyGS;                                           // 0x0298(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ALobbyPS_C*                             LobbyPS;                                           // 0x02A0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ALobby_PlayerController_C*              LobbyPC;                                           // 0x02A8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsStarting;                                        // 0x02B0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2B1[0x7];                                      // 0x02B1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CurrentSave;                                       // 0x02B8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	E_Difficulty                                  CurrentDifficulty;                                 // 0x02C8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_Lobby_Menu(int32 EntryPoint);
	void BndEvt__Lobby_Menu_Lobby_MapSelection_K2Node_ComponentBoundEvent_1_OnSwitched_Difficulty__DelegateSignature(E_Difficulty Difficulty);
	void Construct();
	void BndEvt__Lobby_Menu_ReadyUpBtn_K2Node_ComponentBoundEvent_6_OnButtonClickedEvent__DelegateSignature();
	void CanClose();
	void BndEvt__Lobby_Menu_Lobby_MapSelection_K2Node_ComponentBoundEvent_0_OnSwitched_Save__DelegateSignature(const class FString& SaveName);
	void Init_Casts();
	void Init_Server_ReadyUpBtn();
	void Init_Client_ReadUpBtn();
	void Server_Toggle_Launchevent();
	void Client_Toggle_ReadyUp();
	void Set_Ready_Up_Button(const class FText& Text, bool WarningState_, bool HideButton_, bool LockButton_);
	void Init_ReadyUpButton();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Lobby_Menu_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Lobby_Menu_C")
	}
	static class ULobby_Menu_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULobby_Menu_C>();
	}
};
DUMPER7_ASSERTS_ULobby_Menu_C;

SDK_NAMESPACE_END
