#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Lobby_JoinWithCode_Modal

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "UMG_structs.hpp"
#include "AdvancedSessions_structs.hpp"
#include "OnlineSubsystemUtils_structs.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function Lobby_JoinWithCode_Modal.Lobby_JoinWithCode_Modal_C.ExecuteUbergraph_Lobby_JoinWithCode_Modal
// 0x0270 (0x0270 - 0x0000)
struct Lobby_JoinWithCode_Modal_C_ExecuteUbergraph_Lobby_JoinWithCode_Modal final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_Event_CompleteCallback;                     // 0x0004(0x0010)(ConstParm, ZeroConstructor, NoDestructor)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UFancyUserFlow*                         CallFunc_RunSingleFlowAndWait_CompletedFlowOut;    // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   K2Node_ComponentBoundEvent_Text;                   // 0x0020(0x0018)(ConstParm)
	class UBP_FindSessionFlow_C*                  K2Node_DynamicCast_AsBP_Find_Session_Flow;         // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_41[0x7];                                       // 0x0041(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FBlueprintSessionResult                CallFunc_Array_Get_Item;                           // 0x0048(0x0108)()
	bool                                          Temp_bool_IsClosed_Variable;                       // 0x0150(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_151[0x3];                                      // 0x0151(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetGameTimeInSeconds_ReturnValue;         // 0x0154(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Add_FloatFloat_ReturnValue;               // 0x0158(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetGameTimeInSeconds_ReturnValue_1;       // 0x015C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue;           // 0x0160(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x0161(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_162[0x6];                                      // 0x0162(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   Temp_text_Variable;                                // 0x0168(0x0018)()
	class FText                                   Temp_text_Variable_1;                              // 0x0180(0x0018)()
	bool                                          Temp_bool_Variable;                                // 0x0198(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Has_Been_Initd_Variable;                 // 0x0199(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_19A[0x6];                                      // 0x019A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FSessionsSearchSetting>         CallFunc_CreateFilters_Array;                      // 0x01A0(0x0010)(ReferenceParm)
	class UBP_FindSessionFlow_C*                  CallFunc_SpawnObject_ReturnValue;                  // 0x01B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x01B8(0x0040)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x01F8(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0208(0x0018)()
	class FText                                   CallFunc_GetText_ReturnValue;                      // 0x0220(0x0018)()
	class FString                                 CallFunc_Conv_TextToString_ReturnValue;            // 0x0238(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	int32                                         CallFunc_Len_ReturnValue;                          // 0x0248(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x024C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GreaterEqual_IntInt_ReturnValue;          // 0x024D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_24E[0x2];                                      // 0x024E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   K2Node_Select_Default;                             // 0x0250(0x0018)()
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0268(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_Lobby_JoinWithCode_Modal_C_ExecuteUbergraph_Lobby_JoinWithCode_Modal;

// Function Lobby_JoinWithCode_Modal.Lobby_JoinWithCode_Modal_C.BindCustomModalCompleteCallback
// 0x0010 (0x0010 - 0x0000)
struct Lobby_JoinWithCode_Modal_C_BindCustomModalCompleteCallback final
{
public:
	TDelegate<void()>                             CompleteCallback_0;                                // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, NoDestructor)
};
DUMPER7_ASSERTS_Lobby_JoinWithCode_Modal_C_BindCustomModalCompleteCallback;

// Function Lobby_JoinWithCode_Modal.Lobby_JoinWithCode_Modal_C.BndEvt__Lobby_JoinWithCode_Modal_LobbyCode_TextBox_K2Node_ComponentBoundEvent_2_OnEditableTextBoxChangedEvent__DelegateSignature
// 0x0018 (0x0018 - 0x0000)
struct Lobby_JoinWithCode_Modal_C_BndEvt__Lobby_JoinWithCode_Modal_LobbyCode_TextBox_K2Node_ComponentBoundEvent_2_OnEditableTextBoxChangedEvent__DelegateSignature final
{
public:
	class FText                                   Text;                                              // 0x0000(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_Lobby_JoinWithCode_Modal_C_BndEvt__Lobby_JoinWithCode_Modal_LobbyCode_TextBox_K2Node_ComponentBoundEvent_2_OnEditableTextBoxChangedEvent__DelegateSignature;

// Function Lobby_JoinWithCode_Modal.Lobby_JoinWithCode_Modal_C.OnFocusReceived
// 0x0268 (0x0268 - 0x0000)
struct Lobby_JoinWithCode_Modal_C_OnFocusReceived final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	struct FFocusEvent                            InFocusEvent;                                      // 0x0038(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
	struct FEventReply                            ReturnValue;                                       // 0x0040(0x00B8)(Parm, OutParm, ReturnParm)
	struct FEventReply                            CallFunc_Handled_ReturnValue;                      // 0x00F8(0x00B8)()
	struct FEventReply                            CallFunc_SetUserFocus_ReturnValue;                 // 0x01B0(0x00B8)()
};
DUMPER7_ASSERTS_Lobby_JoinWithCode_Modal_C_OnFocusReceived;

// Function Lobby_JoinWithCode_Modal.Lobby_JoinWithCode_Modal_C.CreateFilters
// 0x00D8 (0x00D8 - 0x0000)
struct Lobby_JoinWithCode_Modal_C_CreateFilters final
{
public:
	TArray<struct FSessionsSearchSetting>         Array;                                             // 0x0000(0x0010)(Parm, OutParm)
	class FName                                   CallFunc_MakeLiteralName_ReturnValue;              // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_TextToString_ReturnValue;            // 0x0018(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetBuildVersionId_ReturnValue;            // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2C[0x4];                                       // 0x002C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSessionPropertyKeyPair                CallFunc_CreateSessionPropertyKeyPair_StringVal_ReturnValue; // 0x0030(0x0020)()
	class FName                                   CallFunc_MakeLiteralName_ReturnValue_1;            // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSessionsSearchSetting                 CallFunc_CreateSessionsSearchSetting_ReturnValue;  // 0x0058(0x0028)()
	struct FSessionPropertyKeyPair                CallFunc_CreateSessionPropertyKeyPair_IntVal_ReturnValue; // 0x0080(0x0020)()
	struct FSessionsSearchSetting                 CallFunc_CreateSessionsSearchSetting_ReturnValue_1; // 0x00A0(0x0028)()
	TArray<struct FSessionsSearchSetting>         K2Node_MakeArray_Array;                            // 0x00C8(0x0010)(ReferenceParm)
};
DUMPER7_ASSERTS_Lobby_JoinWithCode_Modal_C_CreateFilters;

// Function Lobby_JoinWithCode_Modal.Lobby_JoinWithCode_Modal_C.RefreshMessageAndJoinButton
// 0x0050 (0x0050 - 0x0000)
struct Lobby_JoinWithCode_Modal_C_RefreshMessageAndJoinButton final
{
public:
	class UBP_FindSessionFlow_C*                  FindSessionResults;                                // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetMaxPlayers_ReturnValue;                // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_11[0x3];                                       // 0x0011(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_GetCurrentPlayers_ReturnValue;            // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IBPI_UserInterface_C>  CallFunc_ToggleEnabled_self_CastInput;             // 0x0020(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	TScriptInterface<class IBPI_UserInterface_C>  CallFunc_ToggleEnabled_self_CastInput_1;           // 0x0030(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	TScriptInterface<class IBPI_UserInterface_C>  CallFunc_ToggleEnabled_self_CastInput_2;           // 0x0040(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_Lobby_JoinWithCode_Modal_C_RefreshMessageAndJoinButton;

// Function Lobby_JoinWithCode_Modal.Lobby_JoinWithCode_Modal_C.ShowMessage
// 0x0038 (0x0038 - 0x0000)
struct Lobby_JoinWithCode_Modal_C_ShowMessage final
{
public:
	class FText                                   Text;                                              // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
	bool                                          bIsError;                                          // 0x0018(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable;                                // 0x0019(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1A[0x2];                                       // 0x001A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Variable;                                 // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_1;                               // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_1;                              // 0x0024(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_25[0x3];                                       // 0x0025(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         K2Node_Select_Default;                             // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2C[0x4];                                       // 0x002C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UTextBlock*                             K2Node_Select_Default_1;                           // 0x0030(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Lobby_JoinWithCode_Modal_C_ShowMessage;

// Function Lobby_JoinWithCode_Modal.Lobby_JoinWithCode_Modal_C.CleanUpLobbyCodeInput
// 0x0068 (0x0068 - 0x0000)
struct Lobby_JoinWithCode_Modal_C_CleanUpLobbyCodeInput final
{
public:
	class FText                                   InText;                                            // 0x0000(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	class FText                                   CallFunc_TextToUpper_ReturnValue;                  // 0x0018(0x0018)()
	class FString                                 CallFunc_Conv_TextToString_ReturnValue;            // 0x0030(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetSubstring_ReturnValue;                 // 0x0040(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0050(0x0018)()
};
DUMPER7_ASSERTS_Lobby_JoinWithCode_Modal_C_CleanUpLobbyCodeInput;

// Function Lobby_JoinWithCode_Modal.Lobby_JoinWithCode_Modal_C.CustomNavigation_TryJoin
// 0x0020 (0x0020 - 0x0000)
struct Lobby_JoinWithCode_Modal_C_CustomNavigation_TryJoin final
{
public:
	EUINavigation                                 Navigation_0;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                ReturnValue;                                       // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GetIsEnabled_ReturnValue;                 // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_12[0x6];                                       // 0x0012(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UUI_Menu_Button_ProperFocus_C*          K2Node_Select_Default;                             // 0x0018(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Lobby_JoinWithCode_Modal_C_CustomNavigation_TryJoin;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
