#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MP_Level94

#include "Basic.hpp"

#include "AIModule_structs.hpp"
#include "Engine_structs.hpp"
#include "MP_GameMode_classes.hpp"
#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass MP_Level94.MP_Level94_C
// 0x0070 (0x0400 - 0x0390)
class AMP_Level94_C final : public AMP_GameMode_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_MP_Level94_C;                       // 0x0390(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	bool                                          IsNight;                                           // 0x0398(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_399[0x7];                                      // 0x0399(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TMap<int32, class ABPCharacter_Demo_C*>       PlayerMap;                                         // 0x03A0(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FVector                                RetreatLocation;                                   // 0x03F0(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_MP_Level94(int32 EntryPoint);
	void RemoveAnimations();
	void OnQueryFinish(class UEnvQueryInstanceBlueprintWrapper* QueryInstance, EEnvQueryStatus QueryStatus);
	void SpawnAnimations();
	void UserConstructionScript();
	void LoadCheckpoints();
	void ReceiveBeginPlay();
	void OnPlayerSpawn(class ABPCharacter_Demo_C* Player);
	class AActor* ChoosePlayerStart(class AController* Player);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("MP_Level94_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MP_Level94_C")
	}
	static class AMP_Level94_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMP_Level94_C>();
	}
};
DUMPER7_ASSERTS_AMP_Level94_C;

SDK_NAMESPACE_END
