#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Old_Instance

#include "Basic.hpp"

#include "AdvancedSessions_structs.hpp"
#include "OnlineSubsystemUtils_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function Old_Instance.Old_Instance_C.ExecuteUbergraph_Old_Instance
// 0x0820 (0x0820 - 0x0000)
struct Old_Instance_C_ExecuteUbergraph_Old_Instance final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetLocalPlayerController_ReturnValue;     // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FBPUniqueNetId                         CallFunc_GetUniqueNetID_UniqueNetId;               // 0x0010(0x0028)()
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0038(0x0010)(ZeroConstructor, NoDestructor)
	class FName                                   K2Node_CustomEvent_WrittenAchievementName_1;       // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_CustomEvent_WrittenProgress_1;              // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_CustomEvent_WrittenUserTag_1;               // 0x0054(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName WrittenAchievementName, float WrittenProgress, int32 WrittenUserTag)> K2Node_CreateDelegate_OutputDelegate_1; // 0x0058(0x0010)(ZeroConstructor, NoDestructor)
	class FName                                   K2Node_CustomEvent_WrittenAchievementName;         // 0x0068(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_CustomEvent_WrittenProgress;                // 0x0070(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_CustomEvent_WrittenUserTag;                 // 0x0074(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName WrittenAchievementName, float WrittenProgress, int32 WrittenUserTag)> K2Node_CreateDelegate_OutputDelegate_2; // 0x0078(0x0010)(ZeroConstructor, NoDestructor)
	int32                                         Temp_int_Variable;                                 // 0x0088(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable;                               // 0x008C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   Temp_name_Variable;                                // 0x0090(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      K2Node_CustomEvent_PlayerController_4;             // 0x0098(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWidget*                                K2Node_CustomEvent_WidgetRef;                      // 0x00A0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWidget*                                K2Node_CustomEvent_ParentRef_2;                    // 0x00A8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_LevelName;                      // 0x00B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_CustomEvent_MaxPlayer;                      // 0x00B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_IsPrivate;                      // 0x00BC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_BD[0x3];                                       // 0x00BD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   K2Node_CustomEvent_ServerName;                     // 0x00C0(0x0018)()
	class FString                                 CallFunc_Conv_TextToString_ReturnValue;            // 0x00D8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	struct FSessionPropertyKeyPair                CallFunc_MakeLiteralSessionPropertyBool_ReturnValue; // 0x00E8(0x0020)()
	struct FSessionPropertyKeyPair                CallFunc_MakeLiteralSessionPropertyString_ReturnValue; // 0x0108(0x0020)()
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0128(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_129[0x7];                                      // 0x0129(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 K2Node_CustomEvent_Code;                           // 0x0130(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class APlayerController*                      K2Node_CustomEvent_PlayerController_3;             // 0x0140(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWidget*                                K2Node_CustomEvent_ParentRef_1;                    // 0x0148(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_3;            // 0x0150(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0160(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0161(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_162[0x6];                                      // 0x0162(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSessionPropertyKeyPair                CallFunc_MakeLiteralSessionPropertyString_ReturnValue_1; // 0x0168(0x0020)()
	struct FSessionsSearchSetting                 CallFunc_MakeLiteralSessionSearchProperty_ReturnValue; // 0x0188(0x0028)()
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_4;            // 0x01B0(0x0010)(ZeroConstructor, NoDestructor)
	class APlayerController*                      K2Node_CustomEvent_PlayerController_2;             // 0x01C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   K2Node_CustomEvent_Message;                        // 0x01C8(0x0018)()
	class UW_LoadingScreen_C*                     CallFunc_Create_ReturnValue;                       // 0x01E0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x01E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1E9[0x3];                                      // 0x01E9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_5;            // 0x01EC(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_1FC[0x4];                                      // 0x01FC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FBlueprintSessionResult>        Temp_struct_Variable;                              // 0x0200(0x0010)(ReferenceParm)
	struct FBlueprintSessionResult                CallFunc_Array_Get_Item;                           // 0x0210(0x0108)()
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0318(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_31C[0x4];                                      // 0x031C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FBlueprintSessionResult                K2Node_CustomEvent_Session;                        // 0x0320(0x0108)()
	class APlayerController*                      K2Node_CustomEvent_PlayerController_1;             // 0x0428(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWidget*                                K2Node_CustomEvent_ParentRef;                      // 0x0430(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_ShowLoadingScreen;              // 0x0438(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GreaterEqual_IntInt_ReturnValue;          // 0x0439(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_43A[0x6];                                      // 0x043A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UJoinSessionCallbackProxy*              CallFunc_JoinSession_ReturnValue;                  // 0x0440(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x0448(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_449[0x7];                                      // 0x0449(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FBlueprintSessionResult>        K2Node_CustomEvent_Results;                        // 0x0450(0x0010)(ConstParm, ReferenceParm)
	TArray<struct FBlueprintSessionResult>        K2Node_CustomEvent_Results_1;                      // 0x0460(0x0010)(ConstParm, ReferenceParm)
	TDelegate<void(const TArray<struct FBlueprintSessionResult>& Results)> K2Node_CreateDelegate_OutputDelegate_6; // 0x0470(0x0010)(ZeroConstructor, NoDestructor)
	class APlayerController*                      K2Node_CustomEvent_PlayerController;               // 0x0480(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWidget*                                K2Node_CustomEvent_Widget;                         // 0x0488(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UW_MainMenu_C*                          K2Node_DynamicCast_AsW_Main_Menu;                  // 0x0490(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0498(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_4;                    // 0x0499(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_49A[0x2];                                      // 0x049A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(const TArray<struct FBlueprintSessionResult>& Results)> K2Node_CreateDelegate_OutputDelegate_7; // 0x049C(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_8;            // 0x04AC(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_4BC[0x4];                                      // 0x04BC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FBlueprintSessionResult>        Temp_struct_Variable_1;                            // 0x04C0(0x0010)(ReferenceParm)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x04D0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x04D4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4D5[0x3];                                      // 0x04D5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FBlueprintSessionResult>        K2Node_CustomEvent_Results_2;                      // 0x04D8(0x0010)(ConstParm, ReferenceParm)
	struct FSessionPropertyKeyPair                CallFunc_MakeLiteralSessionPropertyString_ReturnValue_2; // 0x04E8(0x0020)()
	struct FSessionsSearchSetting                 CallFunc_MakeLiteralSessionSearchProperty_ReturnValue_1; // 0x0508(0x0028)()
	TArray<struct FSessionsSearchSetting>         K2Node_MakeArray_Array;                            // 0x0530(0x0010)(ConstParm, ReferenceParm)
	TDelegate<void(const TArray<struct FBlueprintSessionResult>& Results)> K2Node_CreateDelegate_OutputDelegate_9; // 0x0540(0x0010)(ZeroConstructor, NoDestructor)
	class UFindSessionsCallbackProxyAdvanced*     CallFunc_FindSessionsAdvanced_ReturnValue;         // 0x0550(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_10;           // 0x0558(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_5;                    // 0x0568(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_569[0x7];                                      // 0x0569(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FBlueprintSessionResult>        K2Node_CustomEvent_Results_3;                      // 0x0570(0x0010)(ConstParm, ReferenceParm)
	struct FSessionPropertyKeyPair                CallFunc_MakeLiteralSessionPropertyBool_ReturnValue_1; // 0x0580(0x0020)()
	TDelegate<void(const TArray<struct FBlueprintSessionResult>& Results)> K2Node_CreateDelegate_OutputDelegate_11; // 0x05A0(0x0010)(ZeroConstructor, NoDestructor)
	TArray<struct FSessionPropertyKeyPair>        K2Node_MakeArray_Array_1;                          // 0x05B0(0x0010)(ConstParm, ReferenceParm)
	class UCreateSessionCallbackProxyAdvanced*    CallFunc_CreateAdvancedSession_ReturnValue;        // 0x05C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSessionPropertyKeyPair                CallFunc_MakeLiteralSessionPropertyBool_ReturnValue_2; // 0x05C8(0x0020)()
	struct FSessionsSearchSetting                 CallFunc_MakeLiteralSessionSearchProperty_ReturnValue_2; // 0x05E8(0x0028)()
	bool                                          CallFunc_IsValid_ReturnValue_6;                    // 0x0610(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_611[0x7];                                      // 0x0611(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FSessionsSearchSetting>         K2Node_MakeArray_Array_2;                          // 0x0618(0x0010)(ConstParm, ReferenceParm)
	class UFindSessionsCallbackProxyAdvanced*     CallFunc_FindSessionsAdvanced_ReturnValue_1;       // 0x0628(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_7;                    // 0x0630(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_Event_bWasSuccessful;                       // 0x0631(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_632[0x2];                                      // 0x0632(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         K2Node_Event_LocalPlayerNum;                       // 0x0634(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FBPUniqueNetId                         K2Node_Event_PersonInvited;                        // 0x0638(0x0028)()
	struct FBlueprintSessionResult                K2Node_Event_SessionToJoin;                        // 0x0660(0x0108)(ConstParm)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_12;           // 0x0768(0x0010)(ZeroConstructor, NoDestructor)
	struct FBPUniqueNetId                         K2Node_Event_PlayerId;                             // 0x0778(0x0028)()
	bool                                          K2Node_Event_bIsTalking;                           // 0x07A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7A1[0x3];                                      // 0x07A1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_13;           // 0x07A4(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          CallFunc_EqualEqual_UNetIDUnetID_ReturnValue;      // 0x07B4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7B5[0x3];                                      // 0x07B5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   K2Node_CustomEvent_AchievementName;                // 0x07B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetLocalPlayerController_ReturnValue_1;   // 0x07C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetLocalPlayerController_ReturnValue_2;   // 0x07C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UDestroySessionCallbackProxy*           CallFunc_DestroySession_ReturnValue;               // 0x07D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAchievementWriteCallbackProxy*         CallFunc_WriteAchievementProgress_ReturnValue;     // 0x07D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_8;                    // 0x07E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_9;                    // 0x07E1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_10;                   // 0x07E2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7E3[0x5];                                      // 0x07E3(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UJoinSessionCallbackProxy*              CallFunc_JoinSession_ReturnValue_1;                // 0x07E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_11;                   // 0x07F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7F1[0x7];                                      // 0x07F1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetLocalPlayerController_ReturnValue_3;   // 0x07F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AMP_PlayerController_C*                 K2Node_DynamicCast_AsMP_Player_Controller;         // 0x0800(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0808(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_809[0x7];                                      // 0x0809(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ALobby_PlayerController_C*              K2Node_DynamicCast_AsLobby_Player_Controller;      // 0x0810(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0818(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_Old_Instance_C_ExecuteUbergraph_Old_Instance;

// Function Old_Instance.Old_Instance_C.UnlockAchievement
// 0x0008 (0x0008 - 0x0000)
struct Old_Instance_C_UnlockAchievement final
{
public:
	class FName                                   AchievementName;                                   // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Old_Instance_C_UnlockAchievement;

// Function Old_Instance.Old_Instance_C.OnPlayerTalkingStateChanged
// 0x0030 (0x0030 - 0x0000)
struct Old_Instance_C_OnPlayerTalkingStateChanged final
{
public:
	struct FBPUniqueNetId                         PlayerId;                                          // 0x0000(0x0028)(BlueprintVisible, BlueprintReadOnly, Parm)
	bool                                          bIsTalking;                                        // 0x0028(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_Old_Instance_C_OnPlayerTalkingStateChanged;

// Function Old_Instance.Old_Instance_C.OnSessionInviteAccepted
// 0x0138 (0x0138 - 0x0000)
struct Old_Instance_C_OnSessionInviteAccepted final
{
public:
	bool                                          bWasSuccessful;                                    // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         LocalPlayerNum;                                    // 0x0004(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FBPUniqueNetId                         PersonInvited;                                     // 0x0008(0x0028)(BlueprintVisible, BlueprintReadOnly, Parm)
	struct FBlueprintSessionResult                SessionToJoin;                                     // 0x0030(0x0108)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_Old_Instance_C_OnSessionInviteAccepted;

// Function Old_Instance.Old_Instance_C.ResetAfterErrorFocus
// 0x0010 (0x0010 - 0x0000)
struct Old_Instance_C_ResetAfterErrorFocus final
{
public:
	class APlayerController*                      PlayerController;                                  // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWidget*                                Widget;                                            // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Old_Instance_C_ResetAfterErrorFocus;

// Function Old_Instance.Old_Instance_C.JoinServerSession
// 0x0120 (0x0120 - 0x0000)
struct Old_Instance_C_JoinServerSession final
{
public:
	struct FBlueprintSessionResult                Session;                                           // 0x0000(0x0108)(BlueprintVisible, BlueprintReadOnly, Parm)
	class APlayerController*                      PlayerController;                                  // 0x0108(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWidget*                                ParentRef;                                         // 0x0110(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ShowLoadingScreen_0;                               // 0x0118(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_Old_Instance_C_JoinServerSession;

// Function Old_Instance.Old_Instance_C.ShowLoadingScreen
// 0x0020 (0x0020 - 0x0000)
struct Old_Instance_C_ShowLoadingScreen final
{
public:
	class APlayerController*                      PlayerController;                                  // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   Message;                                           // 0x0008(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
};
DUMPER7_ASSERTS_Old_Instance_C_ShowLoadingScreen;

// Function Old_Instance.Old_Instance_C.JoinServerCode
// 0x0020 (0x0020 - 0x0000)
struct Old_Instance_C_JoinServerCode final
{
public:
	class FString                                 Code_0;                                            // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	class APlayerController*                      PlayerController;                                  // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWidget*                                ParentRef;                                         // 0x0018(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Old_Instance_C_JoinServerCode;

// Function Old_Instance.Old_Instance_C.CreateServer
// 0x0040 (0x0040 - 0x0000)
struct Old_Instance_C_CreateServer final
{
public:
	class APlayerController*                      PlayerController;                                  // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWidget*                                WidgetRef;                                         // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWidget*                                ParentRef;                                         // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   LevelName;                                         // 0x0018(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         MaxPlayer;                                         // 0x0020(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsPrivate;                                         // 0x0024(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_25[0x3];                                       // 0x0025(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   ServerName;                                        // 0x0028(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
};
DUMPER7_ASSERTS_Old_Instance_C_CreateServer;

// Function Old_Instance.Old_Instance_C.OnSuccess_ED213154495FF5E71DED67A697B987EA
// 0x0010 (0x0010 - 0x0000)
struct Old_Instance_C_OnSuccess_ED213154495FF5E71DED67A697B987EA final
{
public:
	class FName                                   WrittenAchievementName;                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         WrittenProgress;                                   // 0x0008(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         WrittenUserTag;                                    // 0x000C(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Old_Instance_C_OnSuccess_ED213154495FF5E71DED67A697B987EA;

// Function Old_Instance.Old_Instance_C.OnFailure_ED213154495FF5E71DED67A697B987EA
// 0x0010 (0x0010 - 0x0000)
struct Old_Instance_C_OnFailure_ED213154495FF5E71DED67A697B987EA final
{
public:
	class FName                                   WrittenAchievementName;                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         WrittenProgress;                                   // 0x0008(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         WrittenUserTag;                                    // 0x000C(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Old_Instance_C_OnFailure_ED213154495FF5E71DED67A697B987EA;

// Function Old_Instance.Old_Instance_C.OnSuccess_887915044268FE8E01B793860BA0535C
// 0x0010 (0x0010 - 0x0000)
struct Old_Instance_C_OnSuccess_887915044268FE8E01B793860BA0535C final
{
public:
	TArray<struct FBlueprintSessionResult>        Results;                                           // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_Old_Instance_C_OnSuccess_887915044268FE8E01B793860BA0535C;

// Function Old_Instance.Old_Instance_C.OnFailure_887915044268FE8E01B793860BA0535C
// 0x0010 (0x0010 - 0x0000)
struct Old_Instance_C_OnFailure_887915044268FE8E01B793860BA0535C final
{
public:
	TArray<struct FBlueprintSessionResult>        Results;                                           // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_Old_Instance_C_OnFailure_887915044268FE8E01B793860BA0535C;

// Function Old_Instance.Old_Instance_C.OnSuccess_B6FBFD1148DA3110AD7A2090ADB4971D
// 0x0010 (0x0010 - 0x0000)
struct Old_Instance_C_OnSuccess_B6FBFD1148DA3110AD7A2090ADB4971D final
{
public:
	TArray<struct FBlueprintSessionResult>        Results;                                           // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_Old_Instance_C_OnSuccess_B6FBFD1148DA3110AD7A2090ADB4971D;

// Function Old_Instance.Old_Instance_C.OnFailure_B6FBFD1148DA3110AD7A2090ADB4971D
// 0x0010 (0x0010 - 0x0000)
struct Old_Instance_C_OnFailure_B6FBFD1148DA3110AD7A2090ADB4971D final
{
public:
	TArray<struct FBlueprintSessionResult>        Results;                                           // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_Old_Instance_C_OnFailure_B6FBFD1148DA3110AD7A2090ADB4971D;

// Function Old_Instance.Old_Instance_C.GenerateCode
// 0x0058 (0x0058 - 0x0000)
struct Old_Instance_C_GenerateCode final
{
public:
	TArray<class FString>                         CharacterSet;                                      // 0x0000(0x0010)(Edit, BlueprintVisible)
	int32                                         Temp_int_Variable;                                 // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue;             // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_15[0x3];                                       // 0x0015(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class FString>                         K2Node_MakeArray_Array;                            // 0x0020(0x0010)(ReferenceParm)
	int32                                         CallFunc_RandomInteger_ReturnValue;                // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_34[0x4];                                       // 0x0034(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Array_Get_Item;                           // 0x0038(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue;                // 0x0048(0x0010)(ZeroConstructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Old_Instance_C_GenerateCode;

// Function Old_Instance.Old_Instance_C.CheckCodeUnique
// 0x0028 (0x0028 - 0x0000)
struct Old_Instance_C_CheckCodeUnique final
{
public:
	struct FSessionsSearchSetting                 Code_0;                                            // 0x0000(0x0028)(BlueprintVisible, BlueprintReadOnly, Parm)
};
DUMPER7_ASSERTS_Old_Instance_C_CheckCodeUnique;

// Function Old_Instance.Old_Instance_C.ToggleVoiceIngame
// 0x0001 (0x0001 - 0x0000)
struct Old_Instance_C_ToggleVoiceIngame final
{
public:
	bool                                          IsActivated;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_Old_Instance_C_ToggleVoiceIngame;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
