#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: S_ChatMessage

#include "Basic.hpp"

#include "AdvancedSessions_structs.hpp"


SDK_NAMESPACE_START

// UserDefinedStruct S_ChatMessage.S_ChatMessage
// 0x0048 (0x0048 - 0x0000)
struct FS_ChatMessage final
{
public:
	class FString                                 ChatSender_4_C7B4E1F24DE31402E441579224BD4102;     // 0x0000(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 ChatMessage_5_75BB7DC5474425DE927E53B8D831BEA3;    // 0x0010(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
	struct FBPUniqueNetId                         UniqueNetId_8_1B76099E4F752A2643030CB3F2A99FF6;    // 0x0020(0x0028)(Edit, BlueprintVisible)
};
DUMPER7_ASSERTS_FS_ChatMessage;

SDK_NAMESPACE_END
