#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: S_Gamemode

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedStruct S_Gamemode.S_Gamemode
// 0x0040 (0x0040 - 0x0000)
struct FS_Gamemode final
{
public:
	class FText                                   Name_10_C4374AD54D709EF9195964939510C060;          // 0x0000(0x0018)(Edit, BlueprintVisible)
	class FText                                   Description_11_777504BA4C030034AAD238A0EC07E5FD;   // 0x0018(0x0018)(Edit, BlueprintVisible)
	class UTexture2D*                             Image_7_3D9A252B4788A5793498838B3A9D8D61;          // 0x0030(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   StartingMap_6_26633BA641C1367F9E4DAFA5089D1F15;    // 0x0038(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_FS_Gamemode;

SDK_NAMESPACE_END
