#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: S_VineSpline

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedStruct S_VineSpline.S_VineSpline
// 0x0018 (0x0018 - 0x0000)
struct FS_VineSpline final
{
public:
	class USplineComponent*                       SplineComponent_8_643CE76F43866D082DECF9A2B9434A33; // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class USplineMeshComponent*>           SplineMeshComponents_16_DDFB7F204DBF2A940BB1378D03E851EF; // 0x0008(0x0010)(Edit, BlueprintVisible, ContainsInstancedReference)
};
DUMPER7_ASSERTS_FS_VineSpline;

SDK_NAMESPACE_END
