#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_FancyRichChoiceModal

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Backrooms_structs.hpp"
#include "UMG_structs.hpp"
#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass W_FancyRichChoiceModal.W_FancyRichChoiceModal_C
// 0x0060 (0x02D0 - 0x0270)
class UW_FancyRichChoiceModal_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0270(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UUI_Menu_Button_ProperFocus_C*          Button1;                                           // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_Menu_Button_ProperFocus_C*          Button2;                                           // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Header;                                            // 0x0288(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_shadow;                                      // 0x0290(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class URichTextBlock*                         Message;                                           // 0x0298(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Title;                                             // 0x02A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	float                                         AnchorNoHeader;                                    // 0x02A8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         AnchorWithHeader;                                  // 0x02AC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              HeaderVisible;                                     // 0x02B0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              HeaderCollapsed;                                   // 0x02B1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2B2[0x6];                                      // 0x02B2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void()>              OnModalComplete;                                   // 0x02B8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	bool                                          bChoseButton2;                                     // 0x02C8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_W_FancyRichChoiceModal(int32 EntryPoint);
	void BndEvt__W_FancyRichChoiceModal_Button2_K2Node_ComponentBoundEvent_1_OnClick__DelegateSignature();
	void Initialize(const class FText& Title_0, const class FText& Header_0, const class FText& Message_0, const class FText& Button_1, const class FText& Button2_0);
	void BindCustomModalCompleteCallback(const TDelegate<void()>& CompleteCallback);
	void BndEvt__W_FancyModal_Button1_K2Node_ComponentBoundEvent_0_OnClick__DelegateSignature();
	void SetUpMessage(const class FText& Message_0, const class FText& Title_0, const class FText& Header_0, const class FText& Button1Label, const TDelegate<void(EFancyModalButton ClickedButton)>& OnButtonPressed);
	void SetUpChoice(const class FText& Message_0, const class FText& Title_0, const class FText& Header_0, const class FText& Button1Label, const class FText& Button2Label, const TDelegate<void(EFancyModalButton ClickedButton)>& OnButtonPressed);
	struct FEventReply OnFocusReceived(const struct FGeometry& MyGeometry, const struct FFocusEvent& InFocusEvent);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("W_FancyRichChoiceModal_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"W_FancyRichChoiceModal_C")
	}
	static class UW_FancyRichChoiceModal_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_FancyRichChoiceModal_C>();
	}
};
DUMPER7_ASSERTS_UW_FancyRichChoiceModal_C;

SDK_NAMESPACE_END
