#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_FancyRichChoiceModal

#include "Basic.hpp"

#include "Slate_structs.hpp"
#include "SlateCore_structs.hpp"
#include "Backrooms_structs.hpp"
#include "UMG_structs.hpp"
#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function W_FancyRichChoiceModal.W_FancyRichChoiceModal_C.ExecuteUbergraph_W_FancyRichChoiceModal
// 0x01F0 (0x01F0 - 0x0000)
struct W_FancyRichChoiceModal_C_ExecuteUbergraph_W_FancyRichChoiceModal final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   K2Node_Event_Message_1;                            // 0x0008(0x0018)(ConstParm)
	class FText                                   K2Node_Event_Title_1;                              // 0x0020(0x0018)(ConstParm)
	class FText                                   K2Node_Event_Header_1;                             // 0x0038(0x0018)(ConstParm)
	class FText                                   K2Node_Event_Button1Label_1;                       // 0x0050(0x0018)(ConstParm)
	class FText                                   K2Node_Event_Button2Label;                         // 0x0068(0x0018)(ConstParm)
	TDelegate<void(EFancyModalButton ClickedButton)> K2Node_Event_OnButtonPressed_1;                 // 0x0080(0x0010)(ConstParm, ZeroConstructor, NoDestructor)
	class FText                                   K2Node_Event_Message;                              // 0x0090(0x0018)(ConstParm)
	class FText                                   K2Node_Event_Title;                                // 0x00A8(0x0018)(ConstParm)
	class FText                                   K2Node_Event_Header;                               // 0x00C0(0x0018)(ConstParm)
	class FText                                   K2Node_Event_Button1Label;                         // 0x00D8(0x0018)(ConstParm)
	TDelegate<void(EFancyModalButton ClickedButton)> K2Node_Event_OnButtonPressed;                   // 0x00F0(0x0010)(ConstParm, ZeroConstructor, NoDestructor)
	class FText                                   CallFunc_GetText_ReturnValue;                      // 0x0100(0x0018)()
	bool                                          CallFunc_TextIsEmpty_ReturnValue;                  // 0x0118(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_119[0x3];                                      // 0x0119(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_SelectFloat_ReturnValue;                  // 0x011C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0120(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_121[0x3];                                      // 0x0121(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_Event_CompleteCallback;                     // 0x0124(0x0010)(ConstParm, ZeroConstructor, NoDestructor)
	uint8                                         Pad_134[0x4];                                      // 0x0134(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   K2Node_CustomEvent_Title;                          // 0x0138(0x0018)()
	class FText                                   K2Node_CustomEvent_Header;                         // 0x0150(0x0018)()
	class FText                                   K2Node_CustomEvent_Message;                        // 0x0168(0x0018)()
	class FText                                   K2Node_CustomEvent_Button_1;                       // 0x0180(0x0018)()
	class FText                                   K2Node_CustomEvent_Button2;                        // 0x0198(0x0018)()
	class UPanelWidget*                           CallFunc_GetParent_ReturnValue;                    // 0x01B0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCanvasPanelSlot*                       CallFunc_SlotAsCanvasSlot_ReturnValue;             // 0x01B8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FAnchors                               CallFunc_GetAnchors_ReturnValue;                   // 0x01C0(0x0010)(NoDestructor)
	float                                         CallFunc_BreakVector2D_X;                          // 0x01D0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector2D_Y;                          // 0x01D4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              CallFunc_MakeVector2D_ReturnValue;                 // 0x01D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FAnchors                               K2Node_MakeStruct_Anchors;                         // 0x01E0(0x0010)(NoDestructor)
};
DUMPER7_ASSERTS_W_FancyRichChoiceModal_C_ExecuteUbergraph_W_FancyRichChoiceModal;

// Function W_FancyRichChoiceModal.W_FancyRichChoiceModal_C.Initialize
// 0x0078 (0x0078 - 0x0000)
struct W_FancyRichChoiceModal_C_Initialize final
{
public:
	class FText                                   Title_0;                                           // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
	class FText                                   Header_0;                                          // 0x0018(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
	class FText                                   Message_0;                                         // 0x0030(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
	class FText                                   Button_1;                                          // 0x0048(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
	class FText                                   Button2_0;                                         // 0x0060(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
};
DUMPER7_ASSERTS_W_FancyRichChoiceModal_C_Initialize;

// Function W_FancyRichChoiceModal.W_FancyRichChoiceModal_C.BindCustomModalCompleteCallback
// 0x0010 (0x0010 - 0x0000)
struct W_FancyRichChoiceModal_C_BindCustomModalCompleteCallback final
{
public:
	TDelegate<void()>                             CompleteCallback;                                  // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, NoDestructor)
};
DUMPER7_ASSERTS_W_FancyRichChoiceModal_C_BindCustomModalCompleteCallback;

// Function W_FancyRichChoiceModal.W_FancyRichChoiceModal_C.SetUpMessage
// 0x0070 (0x0070 - 0x0000)
struct W_FancyRichChoiceModal_C_SetUpMessage final
{
public:
	class FText                                   Message_0;                                         // 0x0000(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	class FText                                   Title_0;                                           // 0x0018(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	class FText                                   Header_0;                                          // 0x0030(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	class FText                                   Button1Label;                                      // 0x0048(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	TDelegate<void(EFancyModalButton ClickedButton)> OnButtonPressed;                                // 0x0060(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, NoDestructor)
};
DUMPER7_ASSERTS_W_FancyRichChoiceModal_C_SetUpMessage;

// Function W_FancyRichChoiceModal.W_FancyRichChoiceModal_C.SetUpChoice
// 0x0088 (0x0088 - 0x0000)
struct W_FancyRichChoiceModal_C_SetUpChoice final
{
public:
	class FText                                   Message_0;                                         // 0x0000(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	class FText                                   Title_0;                                           // 0x0018(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	class FText                                   Header_0;                                          // 0x0030(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	class FText                                   Button1Label;                                      // 0x0048(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	class FText                                   Button2Label;                                      // 0x0060(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	TDelegate<void(EFancyModalButton ClickedButton)> OnButtonPressed;                                // 0x0078(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, NoDestructor)
};
DUMPER7_ASSERTS_W_FancyRichChoiceModal_C_SetUpChoice;

// Function W_FancyRichChoiceModal.W_FancyRichChoiceModal_C.OnFocusReceived
// 0x0268 (0x0268 - 0x0000)
struct W_FancyRichChoiceModal_C_OnFocusReceived final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	struct FFocusEvent                            InFocusEvent;                                      // 0x0038(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
	struct FEventReply                            ReturnValue;                                       // 0x0040(0x00B8)(Parm, OutParm, ReturnParm)
	struct FEventReply                            CallFunc_Handled_ReturnValue;                      // 0x00F8(0x00B8)()
	struct FEventReply                            CallFunc_SetUserFocus_ReturnValue;                 // 0x01B0(0x00B8)()
};
DUMPER7_ASSERTS_W_FancyRichChoiceModal_C_OnFocusReceived;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
