#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_PlayerBlockList_Button

#include "Basic.hpp"

#include "W_PlayerBlockList_Button_classes.hpp"
#include "W_PlayerBlockList_Button_parameters.hpp"


SDK_NAMESPACE_START

// Function W_PlayerBlockList_Button.W_PlayerBlockList_Button_C.ExecuteUbergraph_W_PlayerBlockList_Button
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_PlayerBlockList_Button_C::ExecuteUbergraph_W_PlayerBlockList_Button(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlayerBlockList_Button_C", "ExecuteUbergraph_W_PlayerBlockList_Button");

	Params::W_PlayerBlockList_Button_C_ExecuteUbergraph_W_PlayerBlockList_Button Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_PlayerBlockList_Button.W_PlayerBlockList_Button_C.OpenBlockList
// (BlueprintCallable, BlueprintEvent)

void UW_PlayerBlockList_Button_C::OpenBlockList()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlayerBlockList_Button_C", "OpenBlockList");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_PlayerBlockList_Button.W_PlayerBlockList_Button_C.BndEvt__W_PlayerBlockList_Button_Button_76_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UW_PlayerBlockList_Button_C::BndEvt__W_PlayerBlockList_Button_Button_76_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlayerBlockList_Button_C", "BndEvt__W_PlayerBlockList_Button_Button_76_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_PlayerBlockList_Button.W_PlayerBlockList_Button_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_PlayerBlockList_Button_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlayerBlockList_Button_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_PlayerBlockList_Button.W_PlayerBlockList_Button_C.Create Menu
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUserWidget*                      ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UUserWidget* UW_PlayerBlockList_Button_C::Create_Menu()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlayerBlockList_Button_C", "Create Menu");

	Params::W_PlayerBlockList_Button_C_Create_Menu Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function W_PlayerBlockList_Button.W_PlayerBlockList_Button_C.OnFocusReceived
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FFocusEvent&               InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UW_PlayerBlockList_Button_C::OnFocusReceived(const struct FGeometry& MyGeometry, const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlayerBlockList_Button_C", "OnFocusReceived");

	Params::W_PlayerBlockList_Button_C_OnFocusReceived Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function W_PlayerBlockList_Button.W_PlayerBlockList_Button_C.RefreshStyle
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UW_PlayerBlockList_Button_C::RefreshStyle()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlayerBlockList_Button_C", "RefreshStyle");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_PlayerBlockList_Button.W_PlayerBlockList_Button_C.OnFocusLost
// (BlueprintCosmetic, Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FFocusEvent&               InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UW_PlayerBlockList_Button_C::OnFocusLost(const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlayerBlockList_Button_C", "OnFocusLost");

	Params::W_PlayerBlockList_Button_C_OnFocusLost Parms{};

	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_PlayerBlockList_Button.W_PlayerBlockList_Button_C.OnKeyDown
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FKeyEvent&                 InKeyEvent                                             (BlueprintVisible, BlueprintReadOnly, Parm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UW_PlayerBlockList_Button_C::OnKeyDown(const struct FGeometry& MyGeometry, const struct FKeyEvent& InKeyEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlayerBlockList_Button_C", "OnKeyDown");

	Params::W_PlayerBlockList_Button_C_OnKeyDown Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InKeyEvent = std::move(InKeyEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function W_PlayerBlockList_Button.W_PlayerBlockList_Button_C.CloseBlockList
// (Public, BlueprintCallable, BlueprintEvent)

void UW_PlayerBlockList_Button_C::CloseBlockList()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlayerBlockList_Button_C", "CloseBlockList");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
