#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_PlayerBlockList

#include "Basic.hpp"

#include "UMG_classes.hpp"
#include "SlateCore_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass W_PlayerBlockList.W_PlayerBlockList_C
// 0x0030 (0x02A0 - 0x0270)
class UW_PlayerBlockList_C final : public UUserWidget
{
public:
	class UScrollBox*                             BlockedPlayerEntriesScrollList;                    // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             ErrorMessage;                                      // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_274;                                         // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TArray<class UW_PlayerBlockList_Entry_C*>     PlayerListEntries;                                 // 0x0288(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	class UW_PlayerBlockList_Button_C*            OwnerBlockListButton;                              // 0x0298(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	struct FEventReply OnFocusReceived(const struct FGeometry& MyGeometry, const struct FFocusEvent& InFocusEvent);
	void Refresh();
	void ShowErrorOrStatusMessage(const class FText& InText);
	struct FEventReply OnKeyDown(const struct FGeometry& MyGeometry, const struct FKeyEvent& InKeyEvent);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("W_PlayerBlockList_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"W_PlayerBlockList_C")
	}
	static class UW_PlayerBlockList_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_PlayerBlockList_C>();
	}
};
DUMPER7_ASSERTS_UW_PlayerBlockList_C;

SDK_NAMESPACE_END
