#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_VOIPIndicator

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"
#include "AdvancedSessions_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass W_VOIPIndicator.W_VOIPIndicator_C
// 0x0040 (0x02B0 - 0x0270)
class UW_VOIPIndicator_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0270(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UTextBlock*                             TextBlock_Username;                                // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_VOIP_Speaker_C*                      W_VOIP_Speaker;                                    // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FBPUniqueNetId                         UniqueId;                                          // 0x0288(0x0028)(Edit, BlueprintVisible, ExposeOnSpawn)

public:
	void ExecuteUbergraph_W_VOIPIndicator(int32 EntryPoint);
	void Construct();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("W_VOIPIndicator_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"W_VOIPIndicator_C")
	}
	static class UW_VOIPIndicator_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_VOIPIndicator_C>();
	}
};
DUMPER7_ASSERTS_UW_VOIPIndicator_C;

SDK_NAMESPACE_END
