#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_Button_Confirmation_Theme2

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Backrooms_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WB_Button_Confirmation_Theme2.WB_Button_Confirmation_Theme2_C.ExecuteUbergraph_WB_Button_Confirmation_Theme2
// 0x0008 (0x0008 - 0x0000)
struct WB_Button_Confirmation_Theme2_C_ExecuteUbergraph_WB_Button_Confirmation_Theme2 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_WB_Button_Confirmation_Theme2_C_ExecuteUbergraph_WB_Button_Confirmation_Theme2;

// Function WB_Button_Confirmation_Theme2.WB_Button_Confirmation_Theme2_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WB_Button_Confirmation_Theme2_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_WB_Button_Confirmation_Theme2_C_PreConstruct;

// Function WB_Button_Confirmation_Theme2.WB_Button_Confirmation_Theme2_C.SetUp
// 0x0001 (0x0001 - 0x0000)
struct WB_Button_Confirmation_Theme2_C_SetUp final
{
public:
	EFancyInputDevice                             CallFunc_GetCurrentInputDevice_ReturnValue;        // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WB_Button_Confirmation_Theme2_C_SetUp;

// Function WB_Button_Confirmation_Theme2.WB_Button_Confirmation_Theme2_C.Set_ButtonStyle
// 0x0460 (0x0460 - 0x0000)
struct WB_Button_Confirmation_Theme2_C_Set_ButtonStyle final
{
public:
	class UTexture2D*                             Normal_Image_0;                                    // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UTexture2D*                             Hovered_Image_0;                                   // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UTexture2D*                             Pressed_Image_0;                                   // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           FontColor;                                         // 0x0018(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            K2Node_MakeStruct_SlateColor;                      // 0x0028(0x0028)()
	struct FSlateBrush                            CallFunc_Get_SlateBrush_SlateBrush;                // 0x0050(0x0088)()
	struct FSlateBrush                            CallFunc_Get_SlateBrush_SlateBrush_1;              // 0x00D8(0x0088)()
	struct FSlateBrush                            CallFunc_Get_SlateBrush_SlateBrush_2;              // 0x0160(0x0088)()
	struct FButtonStyle                           K2Node_MakeStruct_ButtonStyle;                     // 0x01E8(0x0278)()
};
DUMPER7_ASSERTS_WB_Button_Confirmation_Theme2_C_Set_ButtonStyle;

// Function WB_Button_Confirmation_Theme2.WB_Button_Confirmation_Theme2_C.Set_ButtonSize
// 0x0010 (0x0010 - 0x0000)
struct WB_Button_Confirmation_Theme2_C_Set_ButtonSize final
{
public:
	float                                         CallFunc_BreakVector2D_X;                          // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector2D_Y;                          // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Divide_FloatFloat_ReturnValue;            // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Divide_FloatFloat_ReturnValue_1;          // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WB_Button_Confirmation_Theme2_C_Set_ButtonSize;

// Function WB_Button_Confirmation_Theme2.WB_Button_Confirmation_Theme2_C.Get_SlateBrush
// 0x0130 (0x0130 - 0x0000)
struct WB_Button_Confirmation_Theme2_C_Get_SlateBrush final
{
public:
	class UTexture2D*                             Image;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateBrush                            SlateBrush;                                        // 0x0008(0x0088)(Parm, OutParm)
	int32                                         CallFunc_Blueprint_GetSizeX_ReturnValue;           // 0x0090(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Blueprint_GetSizeY_ReturnValue;           // 0x0094(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Conv_IntToFloat_ReturnValue;              // 0x0098(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Conv_IntToFloat_ReturnValue_1;            // 0x009C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              CallFunc_MakeVector2D_ReturnValue;                 // 0x00A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateBrush                            K2Node_MakeStruct_SlateBrush;                      // 0x00A8(0x0088)()
};
DUMPER7_ASSERTS_WB_Button_Confirmation_Theme2_C_Get_SlateBrush;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
