#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_Button_AutoSet_Theme2

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WB_Button_AutoSet_Theme2.WB_Button_AutoSet_Theme2_C.ExecuteUbergraph_WB_Button_AutoSet_Theme2
// 0x0018 (0x0018 - 0x0000)
struct WB_Button_AutoSet_Theme2_C_ExecuteUbergraph_WB_Button_AutoSet_Theme2 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetLocalPlayerController_ReturnValue;     // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsHovered;                            // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_Event_IsEnabled;                            // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_Event_IsFocused;                            // 0x0012(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_WB_Button_AutoSet_Theme2_C_ExecuteUbergraph_WB_Button_AutoSet_Theme2;

// Function WB_Button_AutoSet_Theme2.WB_Button_AutoSet_Theme2_C.ToggleFocus
// 0x0001 (0x0001 - 0x0000)
struct WB_Button_AutoSet_Theme2_C_ToggleFocus final
{
public:
	bool                                          IsFocused;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_WB_Button_AutoSet_Theme2_C_ToggleFocus;

// Function WB_Button_AutoSet_Theme2.WB_Button_AutoSet_Theme2_C.ToggleEnabled
// 0x0001 (0x0001 - 0x0000)
struct WB_Button_AutoSet_Theme2_C_ToggleEnabled final
{
public:
	bool                                          IsEnabled;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_WB_Button_AutoSet_Theme2_C_ToggleEnabled;

// Function WB_Button_AutoSet_Theme2.WB_Button_AutoSet_Theme2_C.ToggleHover
// 0x0001 (0x0001 - 0x0000)
struct WB_Button_AutoSet_Theme2_C_ToggleHover final
{
public:
	bool                                          IsHovered_0;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_WB_Button_AutoSet_Theme2_C_ToggleHover;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
