#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_ChatMessage

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "SlateCore_structs.hpp"
#include "AdvancedSessions_structs.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WB_ChatMessage.WB_ChatMessage_C.ExecuteUbergraph_WB_ChatMessage
// 0x0004 (0x0004 - 0x0000)
struct WB_ChatMessage_C_ExecuteUbergraph_WB_ChatMessage final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WB_ChatMessage_C_ExecuteUbergraph_WB_ChatMessage;

// Function WB_ChatMessage.WB_ChatMessage_C.Set_ChatMessage
// 0x0050 (0x0050 - 0x0000)
struct WB_ChatMessage_C_Set_ChatMessage final
{
public:
	bool                                          CallFunc_IsFiltering_IsFiltering;                  // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsOnSteam_ReturnValue;                    // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3[0x5];                                        // 0x0003(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0008(0x0018)()
	class FString                                 CallFunc_FilterText_FilteredText;                  // 0x0020(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_FilterText_ReturnValue;                   // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_1;          // 0x0038(0x0018)()
};
DUMPER7_ASSERTS_WB_ChatMessage_C_Set_ChatMessage;

// Function WB_ChatMessage.WB_ChatMessage_C.Set_ChatMessage_Color
// 0x0038 (0x0038 - 0x0000)
struct WB_ChatMessage_C_Set_ChatMessage_Color final
{
public:
	struct FLinearColor                           Specified_Color;                                   // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            K2Node_MakeStruct_SlateColor;                      // 0x0010(0x0028)()
};
DUMPER7_ASSERTS_WB_ChatMessage_C_Set_ChatMessage_Color;

// Function WB_ChatMessage.WB_ChatMessage_C.Set_Username_Global
// 0x0150 (0x0150 - 0x0000)
struct WB_ChatMessage_C_Set_Username_Global final
{
public:
	struct FBPUniqueNetId                         NetId;                                             // 0x0000(0x0028)(BlueprintVisible, BlueprintReadOnly, Parm)
	class UFancyOnlineInteractionsSubsystem*      CallFunc_GetGameInstanceSubsystem_ReturnValue;     // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFancyOnlinePlayerStatusHelper*         CallFunc_CreatePlayerStateBoundStatusHelper_ReturnValue; // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetIsLocalPlayer_ReturnValue;             // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_GetPlayerName_ReturnValue;                // 0x0040(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetPlayerRichTextPlatform_ReturnValue;    // 0x0050(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_CensorProfanity_CleanMessageText;         // 0x0060(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_CensorProfanity_ContainsProfanity;        // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_71[0x7];                                       // 0x0071(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0078(0x0018)()
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_1;          // 0x0090(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x00A8(0x0040)(HasGetValueTypeHash)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_1;            // 0x00E8(0x0040)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0128(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0138(0x0018)()
};
DUMPER7_ASSERTS_WB_ChatMessage_C_Set_Username_Global;

// Function WB_ChatMessage.WB_ChatMessage_C.Set_Username_Color
// 0x0038 (0x0038 - 0x0000)
struct WB_ChatMessage_C_Set_Username_Color final
{
public:
	struct FLinearColor                           SpecifiedColor;                                    // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            K2Node_MakeStruct_SlateColor;                      // 0x0010(0x0028)()
};
DUMPER7_ASSERTS_WB_ChatMessage_C_Set_Username_Color;

// Function WB_ChatMessage.WB_ChatMessage_C.IsFiltering
// 0x0018 (0x0018 - 0x0000)
struct WB_ChatMessage_C_IsFiltering final
{
public:
	bool                                          IsFiltering_0;                                     // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetLocalPlayerController_ReturnValue;     // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UChatComponent_C*                       CallFunc_GetComponentByClass_ReturnValue;          // 0x0010(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WB_ChatMessage_C_IsFiltering;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
