#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_SimpleNonModalMessageQueueDisplay

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WB_SimpleNonModalMessageQueueDisplay.WB_SimpleNonModalMessageQueueDisplay_C
// 0x0010 (0x0280 - 0x0270)
class UWB_SimpleNonModalMessageQueueDisplay_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0270(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UVerticalBox*                           NonmodalMessageContainer;                          // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WB_SimpleNonModalMessageQueueDisplay(int32 EntryPoint);
	void AddMessage(const class FText& Message);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WB_SimpleNonModalMessageQueueDisplay_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WB_SimpleNonModalMessageQueueDisplay_C")
	}
	static class UWB_SimpleNonModalMessageQueueDisplay_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWB_SimpleNonModalMessageQueueDisplay_C>();
	}
};
DUMPER7_ASSERTS_UWB_SimpleNonModalMessageQueueDisplay_C;

SDK_NAMESPACE_END
