#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Button_Basic

#include "Basic.hpp"

#include "EModifierKeys_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WBP_Button_Basic.WBP_Button_Basic_C.ExecuteUbergraph_WBP_Button_Basic
// 0x0010 (0x0010 - 0x0000)
struct WBP_Button_Basic_C_ExecuteUbergraph_WBP_Button_Basic final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidgetInteractionComponent*            K2Node_Event_WidgetInteractionComponent;           // 0x0008(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Button_Basic_C_ExecuteUbergraph_WBP_Button_Basic;

// Function WBP_Button_Basic.WBP_Button_Basic_C.SetComponentReference
// 0x0008 (0x0008 - 0x0000)
struct WBP_Button_Basic_C_SetComponentReference final
{
public:
	class UWidgetInteractionComponent*            WidgetInteractionComponent;                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Button_Basic_C_SetComponentReference;

// Function WBP_Button_Basic.WBP_Button_Basic_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WBP_Button_Basic_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_WBP_Button_Basic_C_PreConstruct;

// Function WBP_Button_Basic.WBP_Button_Basic_C.ChangeTextCasing
// 0x0040 (0x0040 - 0x0000)
struct WBP_Button_Basic_C_ChangeTextCasing final
{
public:
	bool                                          Temp_bool_Variable;                                // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetText_ReturnValue;                      // 0x0008(0x0018)()
	bool                                          CallFunc_EqualEqual_TextText_ReturnValue;          // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   K2Node_Select_Default;                             // 0x0028(0x0018)()
};
DUMPER7_ASSERTS_WBP_Button_Basic_C_ChangeTextCasing;

// Function WBP_Button_Basic.WBP_Button_Basic_C.SetButtonText
// 0x0018 (0x0018 - 0x0000)
struct WBP_Button_Basic_C_SetButtonText final
{
public:
	class FText                                   TextToUse;                                         // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
};
DUMPER7_ASSERTS_WBP_Button_Basic_C_SetButtonText;

// Function WBP_Button_Basic.WBP_Button_Basic_C.ChangeTextToSymbols
// 0x0040 (0x0040 - 0x0000)
struct WBP_Button_Basic_C_ChangeTextToSymbols final
{
public:
	bool                                          Temp_bool_Variable;                                // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetText_ReturnValue;                      // 0x0008(0x0018)()
	bool                                          CallFunc_EqualEqual_IgnoreCase_TextText_ReturnValue; // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   K2Node_Select_Default;                             // 0x0028(0x0018)()
};
DUMPER7_ASSERTS_WBP_Button_Basic_C_ChangeTextToSymbols;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
